################################################################################
#
# File:     configuration.py
# Version:  0.9.0
# Author:   Luke de Munk
#
# Brief:    Contains configuration variables for Homesystem.
#
#           More information:
#           https://github.com/LukedeMunk/zyrax-home-main-controller
#
################################################################################
import pytz                                                                     #To declare a timezone
import os                                                                       #For file handling
import json                                                                     #For JSON handling
from language_package_english import *                                          #Import language package
from ConfigurationManager import ConfigurationManager                           #For the dynamic application configuation
from device_model_configurations import *

APPLICATION_VERSION_0_9_0 = "0.9.0"
APPLICATION_VERSION_0_10_0 = "0.10.0"
CURRENT_APPLICATION_VERSION = APPLICATION_VERSION_0_9_0

PRODUCTION_MODE = True
if os.name == "nt":
    PRODUCTION_MODE = False #Production mode off on windows machines (For now)

KEYRING_KEY = None

#Pins
RF_PIN_BCM = 27                                                                 #BCM mode so GPIO27 (pin 13). RF reciever

APPLICATION_NAME = "ZyraX_Home"
DEFAULT_PASSWORD = "ZyraXHomeUser123!"

RF_RECEIVER_PRESENT = False
RF_TRANSMITTER_PRESENT = False

#Credential names
TELEGRAM_SERVICE_NAME = "Telegram_microservice"
WEATHER_SERVICE_NAME = "Weather_microservice"

#Palettes
PALETTE_RANDOM = 0
PALETTE_YELLOW_RED = 1
PALETTE_PURPLE_BLUE = 2
PALETTE_GREEN_BLUE = 3
PALETTE_BLUE_GREEN = 4
PALETTE_CLOUD_COLORS = 10
PALETTE_LAVA_COLORS = 11
PALETTE_OCEAN_COLORS = 12
PALETTE_FOREST_COLORS = 13

PALETTES = [
    {"name": "Random", "value": PALETTE_RANDOM},
    {"name": "Yellow & Red", "value": PALETTE_YELLOW_RED},
    {"name": "Purple & Blue", "value": PALETTE_PURPLE_BLUE},
    {"name": "Green & Blue", "value": PALETTE_GREEN_BLUE},
    {"name": "Blue & Green", "value": PALETTE_BLUE_GREEN},
    {"name": "Clouds", "value": PALETTE_CLOUD_COLORS},
    {"name": "Lava", "value": PALETTE_LAVA_COLORS},
    {"name": "Ocean", "value": PALETTE_OCEAN_COLORS},
    {"name": "Forest", "value": PALETTE_FOREST_COLORS}
]


#Power animations
POWER_ANIMATION_FADE = 0
POWER_ANIMATION_DISSOLVE = 1
POWER_ANIMATION_SWEEP = 2
POWER_ANIMATION_DUAL_SWEEP = 3
NUM_POWER_ANIMATIONS = 4

POWER_ANIMATIONS = [
    {"name": TEXT_FADE, "id" : POWER_ANIMATION_FADE},
    {"name": TEXT_DISSOLVE, "id" : POWER_ANIMATION_DISSOLVE},
    {"name": TEXT_SWEEP, "id" : POWER_ANIMATION_SWEEP},
    {"name": TEXT_DUAL_SWEEP, "id" : POWER_ANIMATION_DUAL_SWEEP}
]

#Tiles
TILE_SIZE_1X1 = 0
TILE_SIZE_1X2 = 1
TILE_SIZE_2X2 = 2
TILE_SIZE_2X4 = 3
TILE_SIZE_4X4 = 4

TILE_TYPE_DEVICE = 0
TILE_TYPE_GROUP = 1
TILE_TYPE_DATETIME = 2
TILE_TYPE_WEATHER = 3
TILE_TYPE_ALARM = 4
TILE_TYPE_AUTOMATION = 5
TILE_TYPE_ADD = 100
TILE_TYPE_SPACER = 101

TILE_TYPES = [
    {"type": TILE_TYPE_DEVICE, "name": TEXT_DEVICE},
    {"type": TILE_TYPE_GROUP, "name": TEXT_GROUP},
    {"type": TILE_TYPE_DATETIME, "name": TEXT_DATE_AND_TIME},
    {"type": TILE_TYPE_WEATHER, "name": TEXT_WEATHER},
    {"type": TILE_TYPE_ALARM, "name": TEXT_ALARM},
    {"type": TILE_TYPE_AUTOMATION, "name": TEXT_AUTOMATION},
]

TIME_ZONE = pytz.timezone("Europe/Amsterdam")

MIN_LEDSTRIP_BRIGHTNESS = 25
MAX_LEDSTRIP_BRIGHTNESS = 255
MAX_NUMBER_OF_LEDS = 250

DEFAULT_FIRMWARE_VERSION = "v0.0.0"
COMPATIBLE_LEDSTRIP_FIRMWARE_VERSIONS = ["v0.0.2", "v0.9.0"]
DEFAULT_IP_ADDRESS = "0.0.0.0"

#Ledstrip mode parameters
PARAMETER_ID_COLOR_RANGE = 1
PARAMETER_ID_COLOR1 = 2
PARAMETER_ID_COLOR2 = 3
PARAMETER_ID_SEGMENT_SIZE = 4
PARAMETER_ID_TAIL_LENGTH = 5
PARAMETER_ID_WAVE_LENGTH = 6
PARAMETER_ID_TIME_FADE = 7
PARAMETER_ID_DELAY = 8
PARAMETER_ID_DELAY_BETWEEN = 9
PARAMETER_ID_RANDOMNESS_DELAY = 10
PARAMETER_ID_INTENSITY = 11
PARAMETER_ID_DIRECTION = 12
PARAMETER_ID_NUMBER_OF_ELEMENTS = 13
PARAMETER_ID_PALETTE = 14
PARAMETER_ID_FADE_LENGTH = 15

MODE_PARAMETER_TYPE_COLOR_RANGE = 0
MODE_PARAMETER_TYPE_COLOR = 1
MODE_PARAMETER_TYPE_CHECKBOX = 2
MODE_PARAMETER_TYPE_RANGE = 3
MODE_PARAMETER_TYPE_DIRECTION_CHECKBOX = 4
MODE_PARAMETER_TYPE_SELECT = 5

#Modes
LEDSTRIP_MODE_ID_COLOR = 1
LEDSTRIP_MODE_ID_FADE = 2
LEDSTRIP_MODE_ID_GRADIENT = 3
LEDSTRIP_MODE_ID_BLINK = 4
LEDSTRIP_MODE_ID_SCAN = 5
LEDSTRIP_MODE_ID_THEATER = 6
LEDSTRIP_MODE_ID_SINE = 7
LEDSTRIP_MODE_ID_BOUNCING_BALLS = 8
LEDSTRIP_MODE_ID_DISSOLVE = 9
LEDSTRIP_MODE_ID_SPARKLE = 10
LEDSTRIP_MODE_ID_FIREWORKS = 11
LEDSTRIP_MODE_ID_FIRE = 12
LEDSTRIP_MODE_ID_SWEEP = 13
LEDSTRIP_MODE_ID_COLOR_TWINKELS = 14
LEDSTRIP_MODE_ID_METEOR_RAIN = 15
LEDSTRIP_MODE_ID_COLOR_WAVES = 16
LEDSTRIP_MODE_ID_DRAWING = 100

LEDSTRIP_MODE_PARAMETER_COLOR_RANGE = {"id": PARAMETER_ID_COLOR_RANGE, "type": MODE_PARAMETER_TYPE_COLOR_RANGE, "name": TEXT_COLOR_RANGE, "default1": "0", "default2": "255", "min": "0", "max": "255"}
LEDSTRIP_MODE_PARAMETER_COLOR1 = {"id": PARAMETER_ID_COLOR1, "type": MODE_PARAMETER_TYPE_COLOR, "name": TEXT_COLOR_1, "default1": "#ffffff", "default2": "False"}
LEDSTRIP_MODE_PARAMETER_COLOR2 = {"id": PARAMETER_ID_COLOR2, "type": MODE_PARAMETER_TYPE_COLOR, "name": TEXT_COLOR_2, "default1": "#000000", "default2": "False"}
LEDSTRIP_MODE_PARAMETER_SEGMENT_SIZE = {"id": PARAMETER_ID_SEGMENT_SIZE, "type": MODE_PARAMETER_TYPE_RANGE, "name": TEXT_SEGMENT_SIZE, "default1": "1", "min": "0", "max": "50"}
LEDSTRIP_MODE_PARAMETER_TAIL_LENGTH = {"id": PARAMETER_ID_TAIL_LENGTH, "type": MODE_PARAMETER_TYPE_RANGE, "name": TEXT_TAIL_LENGTH, "default1": "0", "min": "0", "max": "50"}
LEDSTRIP_MODE_PARAMETER_WAVE_LENGTH = {"id": PARAMETER_ID_WAVE_LENGTH, "type": MODE_PARAMETER_TYPE_RANGE, "name": TEXT_WAVE_LENGTH, "default1": "10", "min": "0", "max": "10"}
LEDSTRIP_MODE_PARAMETER_TIME_FADE = {"id": PARAMETER_ID_TIME_FADE, "type": MODE_PARAMETER_TYPE_RANGE, "name": TEXT_FADE_DELAY2, "default1": "0", "min": "0", "max": "1000"}
LEDSTRIP_MODE_PARAMETER_FADE_DELAY = {"id": PARAMETER_ID_DELAY, "type": MODE_PARAMETER_TYPE_RANGE, "name": TEXT_FADE_DELAY, "default1": "100", "min": "0", "max": "1000"}
LEDSTRIP_MODE_PARAMETER_DELAY_BETWEEN = {"id": PARAMETER_ID_DELAY_BETWEEN, "type": MODE_PARAMETER_TYPE_RANGE, "name": TEXT_DELAY_BETWEEN, "default1": "200", "min": "0", "max": "10000"}
LEDSTRIP_MODE_PARAMETER_RANDOMNESS_DELAY = {"id": PARAMETER_ID_RANDOMNESS_DELAY, "type": MODE_PARAMETER_TYPE_RANGE, "name": TEXT_DELAY_RANDOMNESS, "default1": "0", "min": "0", "max": "100"}
LEDSTRIP_MODE_PARAMETER_INTENSITY = {"id": PARAMETER_ID_INTENSITY, "type": MODE_PARAMETER_TYPE_RANGE, "name": TEXT_INTENSITY, "default1": "1", "min": "0", "max": "10"}
LEDSTRIP_MODE_PARAMETER_DIRECTION = {"id": PARAMETER_ID_DIRECTION, "type": MODE_PARAMETER_TYPE_DIRECTION_CHECKBOX, "name": TEXT_DIRECTION, "default1": "False"}
LEDSTRIP_MODE_PARAMETER_NUMBER_OF_ELEMENTS = {"id": PARAMETER_ID_NUMBER_OF_ELEMENTS, "type": MODE_PARAMETER_TYPE_RANGE, "name": TEXT_NUMBER_OF_ELEMENTS, "default1": "5", "min": "1", "max": "50"}
LEDSTRIP_MODE_PARAMETER_PALETTE = {"id": PARAMETER_ID_PALETTE, "type": MODE_PARAMETER_TYPE_SELECT, "name": TEXT_COLOR_PALETTE, "default1": "0"}
LEDSTRIP_MODE_PARAMETER_FADE_LENGTH = {"id": PARAMETER_ID_FADE_LENGTH, "type": MODE_PARAMETER_TYPE_RANGE, "name": TEXT_FADE_LENGTH, "default1": "10", "min": "0", "max": "50"}

LEDSTRIP_MODE_PARAMETERS = [
    LEDSTRIP_MODE_PARAMETER_COLOR_RANGE,
    LEDSTRIP_MODE_PARAMETER_COLOR1,
    LEDSTRIP_MODE_PARAMETER_COLOR2,
    LEDSTRIP_MODE_PARAMETER_SEGMENT_SIZE,
    LEDSTRIP_MODE_PARAMETER_TAIL_LENGTH,
    LEDSTRIP_MODE_PARAMETER_WAVE_LENGTH,
    LEDSTRIP_MODE_PARAMETER_TIME_FADE,
    LEDSTRIP_MODE_PARAMETER_FADE_DELAY,
    LEDSTRIP_MODE_PARAMETER_DELAY_BETWEEN,
    LEDSTRIP_MODE_PARAMETER_RANDOMNESS_DELAY,
    LEDSTRIP_MODE_PARAMETER_INTENSITY,
    LEDSTRIP_MODE_PARAMETER_DIRECTION,
    LEDSTRIP_MODE_PARAMETER_NUMBER_OF_ELEMENTS,
    LEDSTRIP_MODE_PARAMETER_PALETTE,
    LEDSTRIP_MODE_PARAMETER_FADE_LENGTH
]

LEDSTRIP_MODE_COLOR = {
    "id": LEDSTRIP_MODE_ID_COLOR,
    "name": TEXT_COLOR,
    "parameters": [
        LEDSTRIP_MODE_PARAMETER_COLOR1
    ]
}

LEDSTRIP_MODE_FADE = {
    "id": LEDSTRIP_MODE_ID_FADE,
    "name": TEXT_FADE,
    "parameters": [
        LEDSTRIP_MODE_PARAMETER_COLOR_RANGE,
        LEDSTRIP_MODE_PARAMETER_FADE_DELAY
    ]
}

LEDSTRIP_MODE_GRADIENT = {
    "id": LEDSTRIP_MODE_ID_GRADIENT,
    "name": TEXT_GRADIENT,
    "parameters": [
        LEDSTRIP_MODE_PARAMETER_COLOR_RANGE,
        LEDSTRIP_MODE_PARAMETER_WAVE_LENGTH,
        LEDSTRIP_MODE_PARAMETER_FADE_DELAY
    ]
}

LEDSTRIP_MODE_BLINK = {
    "id": LEDSTRIP_MODE_ID_BLINK,
    "name": TEXT_BLINK,
    "parameters": [
        LEDSTRIP_MODE_PARAMETER_COLOR1,
        LEDSTRIP_MODE_PARAMETER_COLOR2,
        LEDSTRIP_MODE_PARAMETER_FADE_DELAY
    ]
}

LEDSTRIP_MODE_SCAN = {
    "id": LEDSTRIP_MODE_ID_SCAN,
    "name": TEXT_SCAN,
    "parameters": [
        LEDSTRIP_MODE_PARAMETER_COLOR1,
        LEDSTRIP_MODE_PARAMETER_COLOR2,
        LEDSTRIP_MODE_PARAMETER_FADE_DELAY,
        LEDSTRIP_MODE_PARAMETER_SEGMENT_SIZE,
        LEDSTRIP_MODE_PARAMETER_TAIL_LENGTH
    ]
}

LEDSTRIP_MODE_THEATER = {
    "id": LEDSTRIP_MODE_ID_THEATER,
    "name": TEXT_THEATER,
    "parameters": [
        LEDSTRIP_MODE_PARAMETER_COLOR1,
        LEDSTRIP_MODE_PARAMETER_COLOR2,
        LEDSTRIP_MODE_PARAMETER_FADE_DELAY,
        LEDSTRIP_MODE_PARAMETER_SEGMENT_SIZE,
        LEDSTRIP_MODE_PARAMETER_DIRECTION
    ]
}

LEDSTRIP_MODE_SINE = {
    "id": LEDSTRIP_MODE_ID_SINE,
    "name": TEXT_SINE,
    "parameters": [
        LEDSTRIP_MODE_PARAMETER_COLOR1,
        LEDSTRIP_MODE_PARAMETER_COLOR2,
        LEDSTRIP_MODE_PARAMETER_FADE_DELAY,
        LEDSTRIP_MODE_PARAMETER_WAVE_LENGTH,
        LEDSTRIP_MODE_PARAMETER_DIRECTION
    ]
}

LEDSTRIP_MODE_BOUNCING_BALLS = {
    "id": LEDSTRIP_MODE_ID_BOUNCING_BALLS,
    "name": TEXT_BOUNCING_BALLS,
    "parameters": [
        LEDSTRIP_MODE_PARAMETER_COLOR1,
        LEDSTRIP_MODE_PARAMETER_COLOR2,
        LEDSTRIP_MODE_PARAMETER_SEGMENT_SIZE,
        LEDSTRIP_MODE_PARAMETER_NUMBER_OF_ELEMENTS
    ]
}

LEDSTRIP_MODE_DISSOLVE = {
    "id": LEDSTRIP_MODE_ID_DISSOLVE,
    "name": TEXT_DISSOLVE,
    "parameters": [
        LEDSTRIP_MODE_PARAMETER_COLOR1,
        LEDSTRIP_MODE_PARAMETER_COLOR2,
        LEDSTRIP_MODE_PARAMETER_FADE_DELAY,
        LEDSTRIP_MODE_PARAMETER_TIME_FADE,
        LEDSTRIP_MODE_PARAMETER_DELAY_BETWEEN
    ]
}

LEDSTRIP_MODE_SPARKLE = {
    "id": LEDSTRIP_MODE_ID_SPARKLE,
    "name": TEXT_SPARKLE,
    "parameters": [
        LEDSTRIP_MODE_PARAMETER_COLOR1,
        LEDSTRIP_MODE_PARAMETER_COLOR2,
        LEDSTRIP_MODE_PARAMETER_FADE_DELAY,
        LEDSTRIP_MODE_PARAMETER_INTENSITY,
        LEDSTRIP_MODE_PARAMETER_DELAY_BETWEEN,
        LEDSTRIP_MODE_PARAMETER_TIME_FADE
    ]
}

LEDSTRIP_MODE_FIREWORKS = {
    "id": LEDSTRIP_MODE_ID_FIREWORKS,
    "name": TEXT_FIREWORKS,
    "parameters": [
        LEDSTRIP_MODE_PARAMETER_PALETTE,
        LEDSTRIP_MODE_PARAMETER_DELAY_BETWEEN,
        LEDSTRIP_MODE_PARAMETER_RANDOMNESS_DELAY
    ]
}

LEDSTRIP_MODE_FIRE = {
    "id": LEDSTRIP_MODE_ID_FIRE,
    "name": TEXT_FIRE,
    "parameters": [
        LEDSTRIP_MODE_PARAMETER_PALETTE,
        LEDSTRIP_MODE_PARAMETER_FADE_DELAY,
        LEDSTRIP_MODE_PARAMETER_SEGMENT_SIZE
    ]
}

LEDSTRIP_MODE_SWEEP = {
    "id": LEDSTRIP_MODE_ID_SWEEP,
    "name": TEXT_SWEEP,
    "parameters": [
        LEDSTRIP_MODE_PARAMETER_COLOR1,
        LEDSTRIP_MODE_PARAMETER_COLOR2,
        LEDSTRIP_MODE_PARAMETER_FADE_DELAY,
        LEDSTRIP_MODE_PARAMETER_DELAY_BETWEEN,
        LEDSTRIP_MODE_PARAMETER_FADE_LENGTH
    ]
}

LEDSTRIP_MODE_COLOR_TWINKELS = {
    "id": LEDSTRIP_MODE_ID_COLOR_TWINKELS,
    "name": TEXT_COLOR_TWINKELS,
    "parameters": [
        LEDSTRIP_MODE_PARAMETER_PALETTE,
        LEDSTRIP_MODE_PARAMETER_FADE_DELAY,
        LEDSTRIP_MODE_PARAMETER_DELAY_BETWEEN,
        LEDSTRIP_MODE_PARAMETER_TIME_FADE
    ]
}

LEDSTRIP_MODE_METEOR_RAIN = {
    "id": LEDSTRIP_MODE_ID_METEOR_RAIN,
    "name": TEXT_METEOR_RAIN,
    "parameters": [
        LEDSTRIP_MODE_PARAMETER_COLOR1,
        LEDSTRIP_MODE_PARAMETER_SEGMENT_SIZE,
        LEDSTRIP_MODE_PARAMETER_TAIL_LENGTH,
        LEDSTRIP_MODE_PARAMETER_FADE_DELAY,
        LEDSTRIP_MODE_PARAMETER_DELAY_BETWEEN,
        LEDSTRIP_MODE_PARAMETER_RANDOMNESS_DELAY
    ]
}

LEDSTRIP_MODE_COLOR_WAVES = {
    "id": LEDSTRIP_MODE_ID_COLOR_WAVES,
    "name": TEXT_COLOR_WAVES,
    "parameters": [
        LEDSTRIP_MODE_PARAMETER_PALETTE
    ]
}

LEDSTRIP_MODE_DRAWING = {
    "id": LEDSTRIP_MODE_ID_DRAWING,
    "name": TEXT_DRAWING,
    "parameters": []
}

LEDSTRIP_MODES = [
    LEDSTRIP_MODE_COLOR,
    LEDSTRIP_MODE_FADE,
    LEDSTRIP_MODE_GRADIENT,
    LEDSTRIP_MODE_BLINK,
    LEDSTRIP_MODE_SCAN,
    LEDSTRIP_MODE_THEATER,
    LEDSTRIP_MODE_SINE,
    LEDSTRIP_MODE_BOUNCING_BALLS,
    LEDSTRIP_MODE_DISSOLVE,
    LEDSTRIP_MODE_SPARKLE,
    LEDSTRIP_MODE_FIREWORKS,
    LEDSTRIP_MODE_FIRE,
    LEDSTRIP_MODE_SWEEP,
    LEDSTRIP_MODE_COLOR_TWINKELS,
    LEDSTRIP_MODE_METEOR_RAIN,
    LEDSTRIP_MODE_COLOR_WAVES,
    LEDSTRIP_MODE_DRAWING,
]

UI_THEME_DARK_BLUE = 0
UI_THEME_LIGHT_BLUE = 1
UI_THEME_DARK_GREEN = 2
UI_THEME_LIGHT_GREEN = 3

UI_THEMES = [{"id" : UI_THEME_DARK_BLUE, "name" : TEXT_DARK_BLUE},
                {"id" : UI_THEME_LIGHT_BLUE, "name" : TEXT_LIGHT_BLUE},
                {"id" : UI_THEME_DARK_GREEN, "name" : TEXT_DARK_GREEN},
                {"id" : UI_THEME_LIGHT_GREEN, "name" : TEXT_LIGHT_GREEN}]

#Automations
AUTOMATION_ACTION_SET_DEVICE_POWER = "set_device_power"
AUTOMATION_ACTION_SET_LEDSTRIP_COLOR = "set_ledstrip_color"
AUTOMATION_ACTION_SET_LEDSTRIP_MODE = "set_ledstrip_mode"
AUTOMATION_ACTION_COMMAND = "command"

AUTOMATION_ACTIONS = [{"name": TEXT_SET_POWER, "device_types": [DEVICE_TYPE_LEDSTRIP], "function": AUTOMATION_ACTION_SET_DEVICE_POWER},
                        {"name": TEXT_UPDATE_COLOR, "device_types": [DEVICE_TYPE_LEDSTRIP], "function": AUTOMATION_ACTION_SET_LEDSTRIP_COLOR},
                        {"name": TEXT_UPDATE_MODE, "device_types": [DEVICE_TYPE_LEDSTRIP], "function": AUTOMATION_ACTION_SET_LEDSTRIP_MODE}]


AUTOMATION_RUN_STATUS_PENDING = "pending"
AUTOMATION_RUN_STATUS_RUNNING = "running"
AUTOMATION_RUN_STATUS_COMPLETED = "completed"
AUTOMATION_RUN_STATUS_FAILED = "failed"
AUTOMATION_RUN_STATUS_CANCELLED = "cancelled"

AUTOMATION_CONCURRENCY_RESTART = "restart"
AUTOMATION_CONCURRENCY_SINGLE = "single"
AUTOMATION_CONCURRENCY_PARALLEL = "parallel"

AUTOMATION_ERROR_STOP = "stop"
AUTOMATION_ERROR_CONTINUE = "continue"

SUPPORTED_UI_LANGUAGES = [{"id" : 0, "language": TEXT_ENGLISH}]

#region Regex strings
RE_FIRSTNAME = r"^[a-z]{2,50}$"
RE_PREPOSITION = r"^[a-z']{0,3}[ ]?[a-z']{0,3}$"
RE_LASTNAME = r"^[a-z]{2,50}$"
RE_EMAIL = r"^\w+([\.-]?\w+)*@\w+([\.-]?\w+)*(\.\w{2,3})+$"
RE_PASSWORD = r"^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[#$^+=!*()@%&]).{8,64}$"
#endregion

ALLOWED_IMAGE_EXTENSIONS = {".jpg", ".jpeg", ".png", ".gif"}

#HTTP commands
CMD_SET_POWER = "set_power"
CMD_SET_BRIGHTNESS = "set_brightness"
CMD_SET_MODE = "set_mode"
CMD_CONFIG_MODE = "configure_mode"
CMD_SET_POWER_ANIMATION = "set_power_animation"
CMD_REBOOT = "reboot"
CMD_UPDATE_FIRMWARE = "update_firmware"
CMD_SET_CONFIGURATION = "set_configuration"
CMD_GET_STATES = "get_states"
CMD_GET_MODE_CONFIGURATIONS = "get_mode_configurations"
CMD_GET_CONFIGURATION = "get_configuration"
CMD_DRAW_LEDS = "draw_leds"

#OTA states
OTA_STATE_IDLE = 0
OTA_STATE_DOWNLOADING_FIRMWARE = 1
OTA_STATE_INSTALLING_FIRMWARE = 2
OTA_STATE_FINISHED = 3
OTA_STATE_WAITING = 4

NETWORK_IP_RANGE = "192.168.2.1/24"

#Paths config
PATH = os.path.dirname(os.path.realpath(__file__))                              #Current path
DB_FILENAME = "zyrax_home.db"                                                   #File name of database
LOG_FILENAME = "logs.log"                                                       #File name of logs
WEATHER_FILENAME = "weather.json"                                               #File name of weather information
CONFIGURATION_FILENAME = "configuration.conf"
DEFAULT_PROFILE_PICTURE_FILENAME = "default_profile_picture.png"

DATA_DIRECTORY = "data"
OTA_DIRECTORY = "ota"
PROFILE_PICTURES_DIRECTORY = "profile_pictures"
LINUX_SYSTEM_DIRECTORY = os.path.join("/etc", APPLICATION_NAME)
LINUX_DATA_DIRECTORY = os.path.join("/var/lib", APPLICATION_NAME)

if PRODUCTION_MODE:
    DATA_DIRECTORY = os.path.join(LINUX_DATA_DIRECTORY, DATA_DIRECTORY)
    DB_PATH = os.path.join(DATA_DIRECTORY, DB_FILENAME)
    LOGS_PATH = os.path.join(DATA_DIRECTORY, LOG_FILENAME)
    WEATHER_PATH = os.path.join(DATA_DIRECTORY, WEATHER_FILENAME)
    OTA_FILE_DIRECTORY_PATH = os.path.join(DATA_DIRECTORY, OTA_DIRECTORY)
    PROFILE_PICTURES_DIRECTORY_PATH = os.path.join(DATA_DIRECTORY, PROFILE_PICTURES_DIRECTORY)
    CONFIGURATION_FILE_PATH = os.path.join(DATA_DIRECTORY, CONFIGURATION_FILENAME)
    PROFILE_PICTURES_DIRECTORY_PATH = os.path.join(DATA_DIRECTORY, PROFILE_PICTURES_DIRECTORY)
    DEFAULT_PROFILE_PICTURE_PATH = os.path.join(PROFILE_PICTURES_DIRECTORY_PATH, DEFAULT_PROFILE_PICTURE_FILENAME)
else:
    DATA_DIRECTORY = os.path.join(PATH, DATA_DIRECTORY)
    DB_PATH = os.path.join(DATA_DIRECTORY, DB_FILENAME)
    LOGS_PATH = os.path.join(DATA_DIRECTORY, LOG_FILENAME)
    WEATHER_PATH = os.path.join(DATA_DIRECTORY, WEATHER_FILENAME)
    OTA_FILE_DIRECTORY_PATH = os.path.join(DATA_DIRECTORY, OTA_DIRECTORY)
    CONFIGURATION_FILE_PATH = os.path.join(DATA_DIRECTORY, CONFIGURATION_FILENAME)
    PROFILE_PICTURES_DIRECTORY_PATH = os.path.join(DATA_DIRECTORY, PROFILE_PICTURES_DIRECTORY)
    DEFAULT_PROFILE_PICTURE_PATH = os.path.join(PROFILE_PICTURES_DIRECTORY_PATH, DEFAULT_PROFILE_PICTURE_FILENAME)

#HTTP codes
HTTP_CODE_OK = 200
HTTP_CODE_BAD_REQUEST = 400
HTTP_CODE_UNAUTHORIZED = 401
HTTP_CODE_INTERNAL_SERVER_ERROR = 500

#Microservices
TELEGRAM_SERVICE_URL = "http://127.0.0.1:8000"
WEATHER_SERVICE_URL = "http://127.0.0.1:8001"

#endregion


dynamic_config = ConfigurationManager(DATA_DIRECTORY, CONFIGURATION_FILE_PATH, APPLICATION_NAME)
